spring:
  application:
    name: projet

  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/projets
    username: postgres
    password: 000014RM
  jpa:
    hibernate:
      ddl-auto: update
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  flyway:
    locations: db/megration
    baseline-on-migrate: true

application:
  config:
    taches-url: http://localhost:8071/api/taches



